<a href="https://colab.research.google.com/github/Hemavati1/Hemavati1/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Word embedding
from tensorflow.keras.preprocessing.text import one_hot


In [13]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a developer',
      'understand the meaning of words',
      'your videos are good']
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
vocab_size=10000
onehot_repr=[one_hot(words,vocab_size) for words in sent]
onehot_repr

[[7813, 2909, 7299, 6961],
 [7813, 2909, 7299, 4347],
 [7813, 7259, 7299, 684],
 [6655, 322, 2189, 6719, 8378],
 [6655, 322, 2189, 7572],
 [1815, 7813, 4102, 7299, 3770],
 [9398, 6627, 1437, 6719]]

In [15]:
#word embeddig representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

sent_lenth=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_lenth)
print(embedded_docs)

[[   0    0    0    0 7813 2909 7299 6961]
 [   0    0    0    0 7813 2909 7299 4347]
 [   0    0    0    0 7813 7259 7299  684]
 [   0    0    0 6655  322 2189 6719 8378]
 [   0    0    0    0 6655  322 2189 7572]
 [   0    0    0 1815 7813 4102 7299 3770]
 [   0    0    0    0 9398 6627 1437 6719]]


In [22]:
dim=10
model=Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_lenth))
model.compile('adam','mse')
model.summary()
print(model.predict(embedded_docs[0]))
embedded_docs[0]


Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________
1/1 [==============================] - 0s 40ms/step
[[ 0.03642802 -0.03500498 -0.03566885  0.0186584  -0.02547686  0.01166528
  -0.00271664 -0.01920015  0.03841386 -0.02312273]
 [ 0.03642802 -0.03500498 -0.03566885  0.0186584  -0.02547686  0.01166528
  -0.00271664 -0.01920015  0.03841386 -0.02312273]
 [ 0.03642802 -0.03500498 -0.03566885  0.0186584  -0.02547686  0.01166528
  -0.00271664 -0.01920015  0.03841386 -0.02312273]
 [ 0.03642802 -0.03500498 -0.03566885  0.0186584  -0.02547686  0.01166528
  -0.00271664 -0.01920015  0.03841386 -0.02312273]
 [-0.04441822 -0.0486581

array([   0,    0,    0,    0, 7813, 2909, 7299, 6961], dtype=int32)